export const ADDTOFAVORITELAUNCHES = "ADDTOFAVORITELAUNCHES";
export const REMOVEFROMFAVORITELAUNCHES = "REMOVEFROMFAVORITELAUNCHES";

export const ADDTOFAVORITELAUNCHPADS = "ADDTOFAVORITELAUNCHPADS";
export const REMOVEFROMFAVORITELAUNCHPADS = "REMOVEFROMFAVORITELAUNCHPADS";
